### PR TITLE
Contact section

### PR DESCRIPTION
**Pull request by mahbubevan**
I would like to contribute to your project.

### CODE REVIEW

**Comment by omiq17** [comment]
It will be good nice if you wrap everything in a `<div class="contact"> </div>```

**Comment by omiq17** [comment]
oh..sorry.. it's ok... it will merge it soon...

**Comment by omiq17** [comment]
Here it creates some conflicts with my code. So, I have to solve it now...

**Comment by omiq17** [comment]
Conflicts have been resolved and added with a new commit. You are requested to upstream and check the repo. Please make me sure that everything is ok. @mahbubevan  
:smiley: :tada: :ice_cream: :facepunch:

**Comment by omiq17** [comment]
I have got an excellent website to learn Git which is [Git How To](https://githowto.com/)
:smiley: :+1:

**Comment by mahbubevan** [comment]
Nice appearances ... :+1:

**Comment by omiq17** [comment]
thanks...I am closing this pull request

**Pull request closed without merging**
